name: Build and Deploy app

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-later

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Generate image tag base on date and time
              id:  datetime
              uses: echo "::set-output name=tag::$(date +'%Y%d%H%M%S')"

            - name: Login to Dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Builder Docker image
              run: | 
                docker build -t shadowhub/strike:${{ steps.datetime.outputs.tag}} .

            - name: Push Docker image to Docker Hub
              run: | 
                docker push shadowhub/strike:${{ steps.datetime.outputs.tag}}